// SPDX-License-Identifier: MIT
// Hearthbound Hollow — Editor / BMLitShaderPatcher
//
// Vendor-asset patch: LightMap Fusion's BM_Lit.shader (auto-generated by
// Amplify Shader Editor for URP < 14.0.9) ships with TWO multi_compile
// declarations of `_SHADOWS_SOFT` in the same compile block. Unity 6 + URP
// 17.x logs:
//
//   Shader error in 'Hidden/Universal/BM_Lit': Keyword '_SHADOWS_SOFT' is
//   duplicated in several directives. This can lead to unnecessary shader
//   variants. Please remove it from all but one directive.
//
// We can't ship the patched 136 KB shader file directly through our delivery
// channel, so we patch it on import via this AssetPostprocessor instead.
// Idempotent: safe to re-run. Survives LightMap Fusion updates.
//
// The patcher is generic — it scans any imported .shader for the same ASE
// `<140009` legacy block and removes it, so if LightMap Fusion adds more
// similarly-affected shaders in the future, this fix continues to apply.

using System.IO;
using UnityEditor;
using UnityEngine;

namespace HearthboundHollow.EditorTools
{
    public class BMLitShaderPatcher : AssetPostprocessor
    {
        // The exact block that needs removing — uses the ASE `<140009` marker.
        // The vendor shader uses CRLF line endings; we also handle LF in case
        // git normalized them on someone's checkout.
        private const string OldBlockCRLF =
            "\t\t\t/*ase_srp_cond_begin:<140009*/\r\n" +
            "\t\t\t#pragma multi_compile_fragment _ _SHADOWS_SOFT\r\n" +
            "            /*ase_srp_cond_end*/\r\n" +
            "\r\n" +
            "\t\t\t/*ase_srp_cond_begin:>=140009*/\r\n" +
            "\t\t\t#pragma multi_compile_fragment _ _SHADOWS_SOFT _SHADOWS_SOFT_LOW _SHADOWS_SOFT_MEDIUM _SHADOWS_SOFT_HIGH\r\n" +
            "            /*ase_srp_cond_end*/";

        private const string NewBlockCRLF =
            "\t\t\t// Hearthbound patch: removed pre-URP-14.0.9 _SHADOWS_SOFT directive\r\n" +
            "\t\t\t// to fix Unity 6 warning: \"Keyword '_SHADOWS_SOFT' is duplicated in several directives\".\r\n" +
            "\t\t\t// We're on URP 17.2.x — only the new granular variant is needed.\r\n" +
            "\t\t\t#pragma multi_compile_fragment _ _SHADOWS_SOFT _SHADOWS_SOFT_LOW _SHADOWS_SOFT_MEDIUM _SHADOWS_SOFT_HIGH";

        private const string OldBlockLF =
            "\t\t\t/*ase_srp_cond_begin:<140009*/\n" +
            "\t\t\t#pragma multi_compile_fragment _ _SHADOWS_SOFT\n" +
            "            /*ase_srp_cond_end*/\n" +
            "\n" +
            "\t\t\t/*ase_srp_cond_begin:>=140009*/\n" +
            "\t\t\t#pragma multi_compile_fragment _ _SHADOWS_SOFT _SHADOWS_SOFT_LOW _SHADOWS_SOFT_MEDIUM _SHADOWS_SOFT_HIGH\n" +
            "            /*ase_srp_cond_end*/";

        private const string NewBlockLF =
            "\t\t\t// Hearthbound patch: removed pre-URP-14.0.9 _SHADOWS_SOFT directive\n" +
            "\t\t\t// to fix Unity 6 warning: \"Keyword '_SHADOWS_SOFT' is duplicated in several directives\".\n" +
            "\t\t\t// We're on URP 17.2.x — only the new granular variant is needed.\n" +
            "\t\t\t#pragma multi_compile_fragment _ _SHADOWS_SOFT _SHADOWS_SOFT_LOW _SHADOWS_SOFT_MEDIUM _SHADOWS_SOFT_HIGH";

        private static void OnPostprocessAllAssets(
            string[] importedAssets,
            string[] deletedAssets,
            string[] movedAssets,
            string[] movedFromAssetPaths)
        {
            foreach (var path in importedAssets)
            {
                if (path.EndsWith(".shader", System.StringComparison.OrdinalIgnoreCase))
                {
                    TryPatch(path);
                }
            }
        }

        [MenuItem("Hearthbound/Patch ASE Shaders Now", priority = 60)]
        public static void PatchAllNow()
        {
            string[] guids = AssetDatabase.FindAssets("t:Shader", new[] { "Assets" });
            int patchedCount = 0, scannedCount = 0;
            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                if (path.StartsWith("Assets/_Project/")) continue;     // skip our own
                if (!File.Exists(path)) continue;
                scannedCount++;
                if (TryPatch(path))
                {
                    AssetDatabase.ImportAsset(path, ImportAssetOptions.ForceUpdate);
                    patchedCount++;
                }
            }
            Debug.Log($"[Hearthbound/ShaderPatcher] Scanned {scannedCount} vendor shaders. Patched {patchedCount}.");
            EditorUtility.DisplayDialog(
                "Shader Patcher",
                $"Scanned {scannedCount} vendor shaders.\nPatched {patchedCount} with duplicate _SHADOWS_SOFT directive.",
                "OK");
        }

        private static bool TryPatch(string assetPath)
        {
            try
            {
                if (!File.Exists(assetPath)) return false;

                var contents = File.ReadAllText(assetPath);

                // Quick reject if not an ASE shader with the legacy marker.
                if (!contents.Contains("ase_srp_cond_begin:<140009")) return false;

                int crlfCount = CountOccurrences(contents, OldBlockCRLF);
                int lfCount = CountOccurrences(contents, OldBlockLF);
                if (crlfCount == 0 && lfCount == 0) return false;       // already patched or different pattern

                if (crlfCount > 0) contents = contents.Replace(OldBlockCRLF, NewBlockCRLF);
                if (lfCount > 0)   contents = contents.Replace(OldBlockLF, NewBlockLF);

                File.WriteAllText(assetPath, contents);

                Debug.Log($"[Hearthbound/ShaderPatcher] Patched '{assetPath}' " +
                          $"({crlfCount + lfCount} duplicate _SHADOWS_SOFT block(s) removed).");
                return true;
            }
            catch (System.Exception e)
            {
                Debug.LogError($"[Hearthbound/ShaderPatcher] Failed to patch '{assetPath}': {e}");
                return false;
            }
        }

        private static int CountOccurrences(string haystack, string needle)
        {
            if (string.IsNullOrEmpty(haystack) || string.IsNullOrEmpty(needle)) return 0;
            int count = 0, idx = 0;
            while ((idx = haystack.IndexOf(needle, idx, System.StringComparison.Ordinal)) >= 0)
            {
                count++;
                idx += needle.Length;
            }
            return count;
        }
    }
}
